### ISSUE TITLE
Awesome APIs

### ISSUE THREAD

**Issue by briatte** [abhishekbanthia/Public-APIs#110]
I was looking for a list of cool APIs and ended up here.

Wouldn't your list be a nice candidate to the [Awesome Lists](https://github.com/sindresorhus/awesome), as the "curated" headline suggests?

**Comment by abhishekbanthia** [comment]
Hi @briatte , even though I vet the APIs submitted, I've approved almost all pull requests; which means this repo is not a curated list anymore. It's just a simple list of APIs.

When I think of an awesome list, I think of a curated list. I believe the awesome concept is flawed, because generally speaking you just can't be insightful whilst trying to work at the scale "awesome" lists normally work at.

I want to veer away from the awesome phenomenon; And thanks for pointing out, I'll be removing the curated part from the description.
